# Generated by Django 4.2.5 on 2024-02-03 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_cake_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='serives')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Cupcakes', 'Cupcakes'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
