# Generated by Django 4.2.5 on 2023-09-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_customer_country_customer_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order_Item",
            new_name="OrderItem",
        ),
    ]
