# Generated by Django 4.2.5 on 2023-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_order_item_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='country',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
