# Generated by Django 4.2.5 on 2023-11-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('phoneNumber', models.IntegerField()),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
