# Generated by Django 4.2.5 on 2023-11-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
