# Generated by Django 4.2.5 on 2023-12-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('Cupcakes', 'Cupcakes'), ('Bouquets', 'Bouquets'), ('Donuts', 'Donuts'), ('Brownies', 'Brownies')], default='Cakes', max_length=20),
        ),
    ]
