# Generated by Django 4.2.5 on 2025-03-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipping_address',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping_address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Shipping_Address',
        ),
    ]
