# Generated by Django 4.2.5 on 2025-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
