# Generated by Django 4.2.5 on 2025-03-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_product_is_active_product_slug_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
